### ISSUE TITLE
怎么在getx下使用 

### ISSUE THREAD

**Issue by zhouxin1233** [LvKang-insist/flutter_floating#12]
项目使用了getx框架， 在getx的GetView类下， 直接按照demo 中  FloatingManager.createFloating 这种创建方式报错

I/flutter ( 2812): debug- FlutterLog  try-catch:  Null check operator used on a null value   #0      FloatingManager.createFloating (package:hugging_flutter/widget/floating/manager/floating_manager.dart:33:31)

**Comment by LvKang-insist** [comment]
> 项目使用了getx框架， 在getx的GetView类下， 直接按照demo 中 FloatingManager.createFloating 这种创建方式报错
> 
> I/flutter ( 2812): debug- FlutterLog try-catch: Null check operator used on a null value #0 FloatingManager.createFloating (package:hugging_flutter/widget/floating/manager/floating_manager.dart:33:31)

你好，我试了一下，没发现你出现的错误，测试的代码是:https://github.com/LvKang-insist/flutter_floating/blob/master/lib/page.dart，你可以拉一下代码试一下，
另外，你先确定一下你本地的 flutter 版本，3.0 以上和以下引用的依赖是不同的，
如果以上还解决不了，可直接联系我，lv345_y@163.com，微信 15129379467

**Comment by spakerlet** [comment]
这样确实可以在GetView上进行使用，但是build页面的时候，怎么做到和statefulwidget的init中一样，可以实现监听事件的绑定且实现浮动按钮的初始化，而不是单纯的通过点击页面将按钮显示出来。能多写一点关于GetView中绑定监听事件及初始化的示例吗
